project_id = "hrhklzusdctgrwpiacyq"

[functions.mint-token]
verify_jwt = false

[functions.process-trade]
verify_jwt = false

[functions.process-ai-profits]
verify_jwt = false

[functions.select-lucky-wallet]
verify_jwt = false
