project_id = "hrhklzusdctgrwpiacyq"

[functions.mint-token]
verify_jwt = false

[functions.execute-trade]
verify_jwt = false

[functions.ai-profit-sale]
verify_jwt = false

[functions.select-lucky-wallet]
verify_jwt = false
