project_id = "hrhklzusdctgrwpiacyq"

[functions.mint-token]
verify_jwt = false

[functions.execute-trade]
verify_jwt = false

[functions.ai-profit-sale]
verify_jwt = false

[functions.select-lucky-wallet]
verify_jwt = false

[functions.ai-governor]
verify_jwt = false

[functions.mind-think]
verify_jwt = false

[functions.autonomous-heartbeat]
verify_jwt = false

[functions.fetch-twitter-trends]
verify_jwt = false

[functions.fetch-solana-metrics]
verify_jwt = false

[functions.hint-api]
verify_jwt = false

[functions.generate-token-profile]
verify_jwt = false
